server:
  port: 808
  context-path: /mall
spring:
  datasource:
    url: jdbc:mysql://wh.vpclub.cn:43306/wukun
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  type-aliases-package: "cn.vpclub.model"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: info
  file: springboot.log
  path: log


